spring.application.name=conto-corrente

# Configurazione Sorgente Dati PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/nome_tuo_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# Impostazioni JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true